# -*- coding: utf-8 -*-
"""german_traffic_sign_detector_Faster-RCNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hoAKh815d8DVc-RlLaCy-TzqGKG2IygI

Download german traffic signs dataset from Kaggle and unzip the file
"""

KAGGLE_USERNAME = "coco13L"
KAGGLE_KEY      = "KGAT_53cec7361db96f96f349241b84227e8c"

!pip install kaggle -q
!mkdir -p ~/.kaggle
!echo '{"username":"'$KAGGLE_USERNAME'","key":"'$KAGGLE_KEY'"}' > ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d safabouguezzi/german-traffic-sign-detection-benchmark-gtsdb -p /content/

import zipfile

with zipfile.ZipFile("/content/german-traffic-sign-detection-benchmark-gtsdb.zip", "r") as z:
    z.extractall("/content/GTSDB")

import os
import torch
import numpy as np
import pandas as pd
from PIL import Image
from torch.utils.data import Dataset, DataLoader
import torchvision
from torchvision import transforms
from torchvision.models.detection import fasterrcnn_resnet50_fpn
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor

"""Prepare the data for training"""

import pandas as pd

df = pd.read_csv("/content/GTSDB/gt.txt", delimiter=";", header=None,
                 names=["filename", "x1", "y1", "x2", "y2", "class_id"])
print(df.head())
print(df["filename"].nunique()) # 506 images have annotations out of ~600

import shutil
from glob import glob
import os

# create directories for annotated/unannotated images
train_src = "/content/GTSDB/TrainIJCNN2013/TrainIJCNN2013"
annotated_images = "/content/train/annotated"
unannotated_images = "/content/train/unannotated"
os.makedirs(annotated_images, exist_ok=True)
os.makedirs(unannotated_images, exist_ok=True)

# Get set of annotated filenames from df
annotated_filenames = set(df["filename"].unique())

# sort images
for f in glob(os.path.join(train_src, "*.ppm")):
    filename = os.path.basename(f)
    if filename in annotated_filenames:
        shutil.copy(f, annotated_images)
    else:
        shutil.copy(f, unannotated_images)

import random

class Compose:
    def __init__(self, transforms):
        self.transforms = transforms
    def __call__(self, image, target):
        for t in self.transforms:
            image, target = t(image, target)
        return image, target

class ToTensor:
    def __call__(self, image, target):
        image = torchvision.transforms.functional.to_tensor(image)
        return image, target

class RandomHorizontalFlip:
    def __init__(self, prob=0.5):
        self.prob = prob
    def __call__(self, image, target):
        if random.random() < self.prob:
            width, _ = image.size
            image = torchvision.transforms.functional.hflip(image)
            # flip the bounding boxes too
            boxes = target["boxes"]
            boxes[:, [0, 2]] = width - boxes[:, [2, 0]]  # x1, x2 = width - x2, width - x1
            target["boxes"] = boxes
        return image, target

# Define the pipeline
transform = Compose([
    RandomHorizontalFlip(prob=0.5),
    ToTensor()
])

from glob import glob

annots = {}
for _, row in df.iterrows():
    fname = row["filename"]
    if fname not in annots:
        annots[fname] = []
    annots[fname].append([row["x1"], row["y1"], row["x2"], row["y2"], row["class_id"]])

class GTSDBDataset(torch.utils.data.Dataset):
    def __init__(self, root, img_files, annots=None, transforms=None):
      self.img_paths = [os.path.join(root, f) for f in img_files]
      self.root = root
      self.transforms = transforms
      self.annots = annots

    def __len__(self):
        return len(self.img_paths)

    def __getitem__(self, idx):
        img_path = self.img_paths[idx]
        img = Image.open(img_path).convert("RGB")
        img_name = os.path.basename(img_path)

        target = None
        if self.annots and img_name in self.annots:
            labels, bboxes = [], []
            for obj in self.annots[img_name]:
                bboxes.append(obj[:-1])
                labels.append(obj[-1] + 1)
            target = {
                "boxes":  torch.as_tensor(bboxes,  dtype=torch.float32),
                "labels": torch.as_tensor(labels, dtype=torch.int64)
            }

        if self.transforms:
            img, target = self.transforms(img, target)

        return img, target

from sklearn.model_selection import train_test_split

IMG_DIR =  "/content/GTSDB/TrainIJCNN2013/TrainIJCNN2013"

train_transform = Compose([RandomHorizontalFlip(0.5), ToTensor()])
val_transform   = Compose([ToTensor()])

# Split annotated image filenames
all_filenames = list(annots.keys())
train_files, val_files = train_test_split(all_filenames, test_size=0.2, random_state=42)

# Build separate annotation dictionaries for train and val sets
train_annots = {k: annots[k] for k in train_files}
val_annots   = {k: annots[k] for k in val_files}

# Create datasets
train_dataset = GTSDBDataset(IMG_DIR, train_files, annots=train_annots, transforms=train_transform)
val_dataset   = GTSDBDataset(IMG_DIR, val_files,   annots=val_annots,   transforms=val_transform)

# Create DataLoaders
def collate_fn(batch):
    return tuple(zip(*batch))

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True,  collate_fn=collate_fn)
val_loader   = DataLoader(val_dataset,   batch_size=4, shuffle=False, collate_fn=collate_fn)

from torchvision.models.detection import fasterrcnn_resnet50_fpn
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor

NUM_CLASSES = 43 + 1  # 43 traffic sign classes + 1 background (used in the R-CNN)

model = fasterrcnn_resnet50_fpn(weights="DEFAULT")

in_features = model.roi_heads.box_predictor.cls_score.in_features
model.roi_heads.box_predictor = FastRCNNPredictor(in_features, NUM_CLASSES)

device = torch.device("cuda")
model.to(device)

# configurations
epochs = 15
optimizer = torch.optim.SGD(model.parameters(), lr=2e-3, momentum=0.9, weight_decay=5e-4)
lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=3, gamma=0.5) # decreases the learning rate by 0.5 ever 3 steps

"""Now train the model"""

# used for stat tracking (losses)
import requests

url = "https://raw.githubusercontent.com/pytorch/vision/main/references/detection/utils.py"
r = requests.get(url)
with open("utils.py", "wb") as f:
    f.write(r.content)

import utils

def train_batch(batch, model, optimizer, scaler):
    imgs, targets = batch
    imgs    = [img.to(device) for img in imgs]
    targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

    optimizer.zero_grad()
    with torch.amp.autocast(device.type):
        losses = model(imgs, targets)
        loss   = sum(losses.values())

    scaler.scale(loss).backward()
    scaler.step(optimizer)
    scaler.update()
    return loss.item(), losses

@torch.no_grad()
def validate_batch(batch, model):
    imgs, targets = batch
    imgs    = [img.to(device) for img in imgs]
    targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

    model.train()
    with torch.amp.autocast(device.type):
        losses = model(imgs, targets)
        loss   = sum(losses.values())
    return loss.item(), losses

import os

scaler = torch.amp.GradScaler()
model_path = "trial_3.pt"

best_val_loss = float("inf")
start_epoch = 1

if os.path.isfile(model_path):
    checkpoint = torch.load(model_path, map_location=device)
    model.load_state_dict(checkpoint["model"])
    best_val_loss = checkpoint.get("best_val", float("inf"))
    start_epoch = checkpoint.get("epoch", 0) + 1
    print(f"Loaded checkpoint from {model_path}")

for epoch in range(start_epoch, epochs + 1):
    model.train()
    train_loss = 0.0
    for batch in train_loader:
        loss, _ = train_batch(batch, model, optimizer, scaler)
        train_loss += loss

    model.train()
    val_loss = 0.0
    for batch in val_loader:
        loss, _ = validate_batch(batch, model)
        val_loss += loss

    train_loss /= len(train_loader)
    val_loss /= len(val_loader)

    lr_scheduler.step()

    if val_loss < best_val_loss:
        best_val_loss = val_loss

        save_dir = os.path.dirname(model_path)
        if save_dir:
            os.makedirs(save_dir, exist_ok=True)

        torch.save(
            {
                "epoch": epoch,
                "model": model.state_dict(),
                "optimizer": optimizer.state_dict(),
                "scheduler": lr_scheduler.state_dict(),
                "scaler": scaler.state_dict(),
                "best_val": best_val_loss,
                "train_loss": train_loss,
                "val_loss": val_loss,
            },
            model_path,
        )
        print(f"Saved best checkpoint to {model_path}")

    print(
        f"Epoch {epoch}/{epochs} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Val Loss: {val_loss:.4f}"
    )

"""Now test the model"""

# Test directory
test_dir = "/content/GTSDB/TestIJCNN2013/TestIJCNN2013Download"

# Get all test image filenames
test_files = [f for f in os.listdir(test_dir) if f.endswith(".ppm")]

# Initialize test dataset
test_dataset = GTSDBDataset(test_dir, img_files=test_files, annots=None, transforms=val_transform)
test_loader  = DataLoader(test_dataset, batch_size=4, shuffle=False, collate_fn=collate_fn)

# Inference
all_preds = []
model.eval()
with torch.no_grad():
    for imgs, _ in test_loader:
        imgs  = [img.to(device) for img in imgs]
        preds = model(imgs)
        all_preds.extend(preds) # add each prediction to list of overall predictions individually

import matplotlib.pyplot as plt
import matplotlib.patches as patches

def show_predictions(dataset, preds, num_images=5, threshold=0.5):
    fig, axes = plt.subplots(1, num_images, figsize=(20, 5))

    for i in range(num_images):
        img, _ = dataset[i]
        pred   = preds[i]

        # Convert tensor to numpy for display
        img_np = img.permute(1, 2, 0).numpy()

        axes[i].imshow(img_np)

        # Filter by confidence score
        keep = pred["scores"] > threshold
        boxes  = pred["boxes"][keep].cpu().numpy()
        labels = pred["labels"][keep].cpu().numpy()
        scores = pred["scores"][keep].cpu().numpy()

        # Draw each bounding box
        for box, label, score in zip(boxes, labels, scores):
            x1, y1, x2, y2 = box
            width  = x2 - x1
            height = y2 - y1

            rect = patches.Rectangle(
                (x1, y1), width, height,
                linewidth=2, edgecolor="red", facecolor="none"
            )
            axes[i].add_patch(rect)
            axes[i].text(x1, y1 - 5, f"Class {label}: {score:.2f}",
                        color="red", fontsize=8)

        axes[i].axis("off")
        axes[i].set_title(f"Image {i+1}")

    plt.tight_layout()
    plt.show()

# Display first 5 test images with predictions
show_predictions(test_dataset, all_preds, num_images=5, threshold=0.3)